services:
  php:
    image: yiisoftware/yii2-php:8.2-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    environment:
      API_KEY: "${API_KEY}"
    ports:
      - '8000:80'
